version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "No Test to run.."
      - echo "test build"
artifacts:
  files:
    - '**/*'
